title: 'Mr Game and Sweat'
email: mrgameandsweat@gmail.com
timezone: UTC
baseurl: ''
permalink: '/:title/'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: The Mr Game and Sweat Team
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  taylor:
    name: Taylor
    display_name: Taylor
    avatar: 'assets/images/taylor.png'
    email: taylormrgameandsweat@gmail.com
    web:
    twitter:
    description: 'Author and founder of Mr. Game and Sweat. He can be found running on a treadmill with an xbox controller in hand playing Balatro most days of the week'
  jonas:
    name: Jonas
    display_name: Jonas
    avatar: 'assets/images/jonas.png'
    email: jonasmrgameandsweat@gmail.com
    web:
    twitter:
    description: 'Jonas is an experienced writer and gamer. He loves Diablo IV, the NBA 2k series, and Fallout 4. He mostly games while riding his exercise bike and watching the latest sports news.'
  megan:
    name: megan
    display_name: megan
    avatar: 'assets/images/megan.png'
    email: meganmrgameandsweat@gmail.com
    web:
    twitter:
    description: 'Megan enjoys playing games like Stardew Valley, Vampire Survivors, and XCOM 2. If its raining you know Megan is gaming while walking on her treadmill..'

# Social
social:
  steam: https://store.steampowered.com/curator/1850-Mr-Game-and-Sweat/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
